package maincontroller.maincommunications.proccessknownewconnection.packages;

import maincontroller.maincommunications.packages.PackageMainCommunications;

public interface PackageProccessKnowNewConnection extends PackageMainCommunications {

}
